### ISSUE TITLE
some questions about  get_and_upload_guest_account.mjs 

### ISSUE THREAD

**Issue by OleaSTeROleaSTeR** [BANKA2017/twitter-monitor#17]
hi all,

My first question is can we put HTTPS proxies in `proxy.txt` ???

when I run 'get_and_upload_guest_account.mjs' it always finds 0 account .
I always have the same answer:

`autonia@wayne:~$ node /home/autonia/opt/banka/twitter-monitor/apps/open_account/scripts/get_and_upload_guest_account.mjs
[Wed Mar 27 2024 01:29:09 GMT-0700 (Pacific Daylight Time)]: #GuestToken Update open account
[Wed Mar 27 2024 01:29:09 GMT-0700 (Pacific Daylight Time)]: #GuestToken Update guest token #Bearer AAAAAAAAAAAAAAAAAAAAAFXzAwAAAAAAMHCxpeSDG1gLNLghVe8d74hl6k4%3DRUMF4xAQLsbeBhTSRrCiQpJtxoGWeyHrDb5te2jpGskWDFW82F
TypeError: Cannot read properties of undefined (reading 'oauth_token')
    at GuestToken.openAccountInit (file:///home/autonia/opt/banka/twitter-monitor/libs/core/Core.function.mjs:74:90)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///home/autonia/opt/banka/twitter-monitor/apps/open_account/scripts/get_and_upload_guest_account.mjs:33:9
count: 1
open_account: No guest account`

I wonder if I missed something in my configuration

in 'Backend (Cloudflare Workers)' 
i must edit the file 'backend/wrangler.toml' and replace '<YOUR_ID>'  by the ID given by cloudflare after creating the  kv space named 'twitter-monitor-workers-kv'  like this :
`kv_namespaces = [
    { binding = "open_accounts", preview_id = "NOT_NECESSARY_TO_CHANGE_THIS_VALUE_KV", id = "20e51c53ad77777ba75a7b6f44cf1f2a" }
`

the `<SECRET_TOKEN>`  is a key completely invented by myself, I just have to put the same key in both files, like this

in `backend/.dev.vars`
`SECRET_WORKERS_KEY="7buwum7PFiFumFRQinZBhz5qWDk4qakjo$QoTi5f"`

in `scripts/get_and_upload_guest_account.mjs`
`const key = '7buwum7PFiFumFRQinZBhz5qWDk4qa*kjo$QoTi5f'
`

in `scripts/get_and_upload_guest_account.mjs`
if the `const endpoint=` link replies 'hello world' then everything is good with the configuration on Cloudflare
`const endpoint = 'https://worker-winter-bush-156a.oleaster.workers.dev/upload/account'`

**Comment by BANKA2017** [comment]
Only 0 accounts were found is because Twitter no longer provide guest accounts. This problem cannot be solved using a proxy.

You can read [zedeus/nitter/issues/983](https://github.com/zedeus/nitter/issues/983) to learn about what happened in the last six months.

**Comment by OleaSTeROleaSTeR** [comment]
thanks for your answer..
I've been using nitter for a long time, but I'm really having trouble keeping up. 
I was hoping that we could still create guest_accounts with your script.
so there is no longer any solution  :(
